from enum import StrEnum


class Permission(StrEnum):
    REPOSITORY_VIEW = "REPOSITORY_VIEW"
    CODE_ANALYZE = "CODE_ANALYZE"
    CHANGE_PROPOSE = "CHANGE_PROPOSE"
    RUNTIME_ANALYZE = "RUNTIME_ANALYZE"
    PATCH_VERIFY = "PATCH_VERIFY"
    PATCH_APPROVE = "PATCH_APPROVE"
    PATCH_APPLY = "PATCH_APPLY"
    HISTORY_VIEW = "HISTORY_VIEW"


class PatchState(StrEnum):
    PROPOSED = "PROPOSED"
    APPLIED_TO_WORKTREE = "APPLIED_TO_WORKTREE"
    PATCH_APPLY_FAILED = "PATCH_APPLY_FAILED"
    VERIFYING = "VERIFYING"
    VERIFIED = "VERIFIED"
    FAILED = "FAILED"
    INCONCLUSIVE = "INCONCLUSIVE"
    APPROVED = "APPROVED"
    STALE_VERIFICATION = "STALE_VERIFICATION"
    APPLIED = "APPLIED"


class CheckStatus(StrEnum):
    PASS = "PASS"
    FAIL = "FAIL"
    INCONCLUSIVE = "INCONCLUSIVE"
    NOT_AVAILABLE = "NOT_AVAILABLE"
    NOT_APPLICABLE = "NOT_APPLICABLE"


class Classification(StrEnum):
    NORMAL = "NORMAL"
    SENSITIVE = "SENSITIVE"
    PROTECTED = "PROTECTED"
