from enum import StrEnum


class ErrorCode(StrEnum):
    INVALID_INPUT = "INVALID_INPUT"
    IDENTITY_UNRESOLVED = "IDENTITY_UNRESOLVED"
    SESSION_INVALID = "SESSION_INVALID"
    ACCESS_DENIED = "ACCESS_DENIED"
    NOT_A_GIT_REPOSITORY = "NOT_A_GIT_REPOSITORY"
    REPOSITORY_UNREGISTERED = "REPOSITORY_UNREGISTERED"
    REPOSITORY_IDENTITY_CHANGED = "REPOSITORY_IDENTITY_CHANGED"
    REPOSITORY_STATE_BLOCKED = "REPOSITORY_STATE_BLOCKED"
    DIRTY_WORKTREE_BLOCKED = "DIRTY_WORKTREE_BLOCKED"
    SAFE_GIT_POLICY_BLOCKED = "SAFE_GIT_POLICY_BLOCKED"
    CRITICAL_PERSISTENCE_FAILED = "CRITICAL_PERSISTENCE_FAILED"
    SCHEMA_VERSION_UNSUPPORTED = "SCHEMA_VERSION_UNSUPPORTED"
    INVALID_STATE_TRANSITION = "INVALID_STATE_TRANSITION"
    IDEMPOTENCY_CONFLICT = "IDEMPOTENCY_CONFLICT"
    PATCH_NOT_READY_FOR_VERIFICATION = "PATCH_NOT_READY_FOR_VERIFICATION"
    PATCH_NOT_VERIFIED = "PATCH_NOT_VERIFIED"
    AMBIGUOUS_PATCH_SELECTION = "AMBIGUOUS_PATCH_SELECTION"
    VERIFICATION_BASIS_MISMATCH = "VERIFICATION_BASIS_MISMATCH"
    PROTECTED_STORAGE_UNAVAILABLE = "PROTECTED_STORAGE_UNAVAILABLE"
    UNSUPPORTED_PLATFORM = "UNSUPPORTED_PLATFORM"
    CAPABILITY_NOT_AVAILABLE = "CAPABILITY_NOT_AVAILABLE"


class DomainError(Exception):
    """Public errors contain trusted explanations, never raw credentials or source."""

    def __init__(self, code: ErrorCode, message: str = "") -> None:
        self.code = code
        self.message = message or code.value
        super().__init__(self.message)
